version: '3'

services:
    screen:
        build: .
        container_name: screen
        command: npm run build
        ports:
            - "80:8080"
        volumes:
            - ./src/:/usr/src/src
            - ./public/:/usr/src/public
